# F5TTS_v1_Base | E2TTS_Base
model = "F5TTS_v1_Base"
ckpt_file = "ckpts/F5TTS_v1_Base_accent_tune/F5TTS_v1_Base_accent_tune/model_last_inference.safetensors"
ref_audio = "infer/examples/basic/roma0.wav"
# If an empty "", transcribes the reference audio automatically.
ref_text = "М+яу , М+яу , М+яу , М+яу , М+яу , прив+ет , я Р+ома, пью пульс+ап , зап+исываю голосов+ое для Д+ани на 12 сек+унд жел+ательно "
gen_text = "Это Я Н+айн М+айс , мне не Хват+ает Т+ысячи Рубл+ей , скинь Ж+опу "
# File with text to generate. Ignores the text above.
gen_file = ""
remove_silence = false
output_dir = "tests"
output_file = "infer_cli_basic_accent.wav"
